#!/usr/bin/env bash
set -e -o pipefail

# Add repo specific metadata here.

PACKAGE_NAME="Transmission"
PACKAGES_FILE_PACKAGE_NAME="transmission-daemon"
RELEASE_PACKAGE_NAME="Transmission"
RELEASE_TAG_PACKAGE_NAME="transmission"
UPSTREAM_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"
TEST_TYPE="foreground"
TEST_CONTAINER_TYPE="transmission"

current_upstream_version() {
    get_packages_install_package_version "${PACKAGES_FILE_PACKAGE_NAME:?}"
}

latest_upstream_version() {
    make update_packages >/dev/null 2>&1
    get_packages_install_package_version "${PACKAGES_FILE_PACKAGE_NAME:?}"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    echo "Updating ${PACKAGE_NAME:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    git add ${PACKAGES_INSTALL_FILE:?}
}

package_current_release_version() {
    current_upstream_version
}

test_start_container() {
    local container_name="${1:?}"
    # TODO: Add testing logic here.
}
